import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Navbar from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {children} ) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {/* Full viewport container */}
          <div className="fixed inset-0 overflow-hidden">
            {/* Navbar */}
            <div className="absolute top-0 left-0 right-0 z-50">
              <Navbar />
            </div>
            
            {/* Main content area - full screen, no scrolling */}
            <main className="absolute inset-0 top-16 overflow-hidden">
              {children}
            </main>
          </div>
        </ThemeProvider>
       
       
      </body>
    </html>
  );
}
